- name: Run Java
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: latest

# 👉 ADD THIS TASK TO INSTALL PyMySQL ON THE MYSQL SERVER
- name: Install PyMySQL on MySQL server
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: present
  become: true
  delegate_to: mysql-dev.ashishlavale5.online

# 👉 GRANT REMOTE CONNECTIONS TO MYSQL
- name: Allow remote connections for MySQL root user from shipping server
  community.mysql.mysql_user:
    name: root
    host: shipping.internal.cloudapp.net
    password: RoboShop@1
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root  # Add this
    login_password: RoboShop@1  # Add this
  delegate_to: mysql-dev.ashishlavale5.online

- name: Ensure MySQL is listening on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/my.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  become: true
  delegate_to: mysql-dev.ashishlavale5.online

- name: Restart MySQL to apply config changes
  ansible.builtin.service:
    name: mysqld
    state: restarted
  become: true
  delegate_to: mysql-dev.ashishlavale5.online

- name: Load to DB
  ansible.builtin.shell: mysql -h mysql-dev.ashishlavale5.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup