#component_name=dispatch
#source common.sh
#
#golang
#
#go mod init dispatch
#go get
#go build
#
#systemd_setup

- name: Run Golang
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup